DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id SERIAL PRIMARY KEY,
  cover VARCHAR(50),
	title VARCHAR(50),
	published DATE,
	author VARCHAR(50),
	description TEXT
);
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x247.bmp/ff4444/ffffff', 'Gus', '12/16/1938', 'Andreas Ivamy', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x222.bmp/5fa2dd/ffffff', 'Flirt', '4/29/1976', 'Arlana Grinvalds', 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x207.jpg/ff4444/ffffff', 'The Italian Connection', '11/30/1966', 'Gaynor McIndrew', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x223.bmp/dddddd/000000', 'Abandon Ship! (Seven Waves Away)', '1/12/2000', 'Marcia Toping', 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x244.png/cc0000/ffffff', 'Han Gong-ju', '10/18/1986', 'Lizabeth Owbrick', 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x238.bmp/5fa2dd/ffffff', 'Violet & Daisy', '9/27/1899', 'Hale Wakely', 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x237.jpg/5fa2dd/ffffff', 'Hart of London, The', '4/11/1922', 'Nixie Trimnell', 'vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x223.jpg/ff4444/ffffff', 'Something the Lord Made', '7/7/1993', 'Alene Whimper', 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x231.png/dddddd/000000', 'Into the Woods', '7/6/1950', 'Miles Eborn', 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x200.png/5fa2dd/ffffff', 'Chamber of Death (Chambre des morts, La)', '2/8/1996', 'Amelina Clingoe', 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x221.png/5fa2dd/ffffff', 'Lilo & Stitch', '3/15/1920', 'Boris Barendtsen', 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x249.jpg/ff4444/ffffff', 'Wild Angels, The', '1/2/1998', 'Georgiana Malenoir', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x229.jpg/cc0000/ffffff', 'When Night Is Falling', '12/11/1953', 'Mathew Strathman', 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x200.bmp/5fa2dd/ffffff', 'Time Stood Still (Il tempo si è fermato)', '4/11/2006', 'Beck Grotty', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x238.jpg/dddddd/000000', 'Ween Live in Chicago', '4/18/1886', 'Carlye Andriveaux', 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x239.jpg/dddddd/000000', 'Prestige, The', '3/16/1890', 'Hillary Meadus', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x225.jpg/dddddd/000000', 'Cold Comes the Night', '8/25/2009', 'Sandye Mollindinia', 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x220.jpg/5fa2dd/ffffff', 'Silk Stockings', '8/12/2004', 'Aloin Wegner', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x215.jpg/5fa2dd/ffffff', 'Different from You and Me (Anders als du und ich) ', '10/18/1946', 'Annamarie Kunisch', 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x216.bmp/5fa2dd/ffffff', 'Assassin Next Door, The (Kirot)', '10/28/1938', 'Price Gounot', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x232.jpg/dddddd/000000', 'Skylark', '11/12/1863', 'Glad Bollum', 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x225.png/5fa2dd/ffffff', 'Land of Happines (Onnen maa)', '6/10/1931', 'Mirilla Rape', 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x224.png/dddddd/000000', 'Soul Kitchen', '3/31/1998', 'Ferrel Gibbon', 'etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x208.bmp/ff4444/ffffff', 'Turn Me On, Dammit! (Få meg på, for faen)', '8/25/1958', 'Adelheid Whetson', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x213.png/ff4444/ffffff', 'Monty Python: Almost the Truth - Lawyers Cut', '5/17/1975', 'Nadia Beacham', 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x232.png/5fa2dd/ffffff', 'Graceland', '4/21/1852', 'Daffi Samworth', 'nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x206.png/dddddd/000000', 'Lackawanna Blues', '4/17/1939', 'Dwight Darlington', 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x225.jpg/dddddd/000000', 'Chuck Berry Hail! Hail! Rock ''n'' Roll', '10/29/1884', 'Vincents Bicker', 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x218.bmp/ff4444/ffffff', 'Kvarteret Skatan reser till Laholm', '9/22/2013', 'Cord Dewire', 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x218.png/cc0000/ffffff', 'Casanova', '11/7/1914', 'Deloria Ferenc', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x233.bmp/ff4444/ffffff', 'Bohème, La', '11/27/1981', 'Clotilda Buttrey', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x240.jpg/5fa2dd/ffffff', 'Remember the Day', '11/16/1953', 'Cary Lamminam', 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x223.bmp/dddddd/000000', 'King of California', '5/3/1947', 'Gennifer Beels', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x239.png/cc0000/ffffff', 'House', '9/21/1937', 'Corissa Trolley', 'ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x231.png/dddddd/000000', 'Hour of the Furnaces, The (Hora de los hornos, La)', '10/21/1865', 'Clyve Leuty', 'quisque arcu libero rutrum ac lobortis vel dapibus at diam');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x219.png/dddddd/000000', 'Dune', '10/16/1941', 'Brianna Bollon', 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x242.png/ff4444/ffffff', 'Cameraman''s Revenge', '2/6/1945', 'Emmy Greensides', 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x237.jpg/5fa2dd/ffffff', 'Rich Man''s Wife, The', '7/28/1950', 'Patrick Mewett', 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x224.jpg/cc0000/ffffff', 'Frisco Kid, The', '1/3/1966', 'Bill Labin', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x232.png/cc0000/ffffff', 'True Meaning of Christmas Specials, The', '5/7/1898', 'Barbaraanne Turnor', 'nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x232.bmp/cc0000/ffffff', 'Beast from 20,000 Fathoms, The', '8/12/1962', 'Leesa Hanaby', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x200.jpg/ff4444/ffffff', 'Wrestling (Bræðrabylta)', '7/17/1867', 'Jarib De Michetti', 'mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x240.bmp/ff4444/ffffff', 'The Raid 2: Berandal', '10/9/1942', 'Karna Lohde', 'pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x206.png/5fa2dd/ffffff', 'Every Which Way But Loose', '8/29/1875', 'Cy Muzzollo', 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x223.bmp/dddddd/000000', 'Tucker & Dale vs Evil', '9/25/1897', 'Ross Soden', 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x218.bmp/5fa2dd/ffffff', 'Almost Heroes', '10/7/1998', 'Raye Eagar', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x202.jpg/5fa2dd/ffffff', 'Woman''s Face, A', '8/21/1951', 'Kelsey Dennistoun', 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x247.jpg/ff4444/ffffff', 'Living on One Dollar', '7/16/1971', 'Jeannette Janse', 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x212.png/ff4444/ffffff', 'True Colors', '9/11/1955', 'Bab Branscomb', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices');
insert into books (cover, title, published, author, description) values ('http://dummyimage.com/x220.png/cc0000/ffffff', 'May Fools (Milou en mai)', '10/25/1917', 'Nadiya Abercromby', 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer');
